name: Update README cards

on:
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&theme=dark&include_all_commits=true
          path: profile/stats.svg
          token: ${{ secrets.PAT }}

      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          USERNAME: ${{ github.repository_owner }}
          OUTPUT_DIR: profile
          UTCTIMEZONE: "America/Los_Angeles"

      - name: Commit cards
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git add profile/*.svg profile/*.png
          git commit -m "Update README cards" || exit 0
          git push origin main
